from slash.core import Elem
from slash.html import (
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    HTML,
    A,
    Br,
    Button,
    Code,
    Details,
    Dialog,
    Div,
    Img,
    Input,
    Label,
    Li,
    Ol,
    P,
    Pre,
    Select,
    Span,
    Summary,
    Table,
    Td,
    Textarea,
    Th,
    Tr,
    Ul,
)
from slash.layout import Column


def test_html() -> Elem:
    return Div(
        P("This page tests all elements in ", Code("slash.html"), "."),
        H3(Code("A")),
        A("This is an <a> element.", href="https://github.com/jessetvogel/slash"),
        Br(),
        A("This is an <a> element with target _blank.", href="https://github.com/jessetvogel/slash", target="_blank"),
        H3(Code("Br")),
        Div("There is a <br> element between this line", Br(), "and this line."),
        H3(Code("Button")),
        Button("This is a <button> element."),
        H3(Code("Code")),
        Code("This is a <code> element."),
        H3(Code("Details"), " and ", Code("Summary")),
        Details(Summary("This is a <summary> element."), P("This is inside the <details> element.")),
        H3(Code("Dialog")),
        dialog := Dialog(Column(P("This is a <dialog> element."), Button("Close").onclick(lambda: dialog.close()))),
        Button("Click here to show the <dialog> element").onclick(lambda: dialog.show_modal()),
        H3(Code("Div")),
        Div("This is a <div> element."),
        H3(Code("H1"), ", ", Code("H2"), ", ", Code("H3"), ", ", Code("H4"), ", ", Code("H5"), " and ", Code("H6")),
        H1("This is an <h1> element."),
        H2("This is an <h2> element."),
        H3("This is an <h3> element."),
        H4("This is an <h4> element."),
        H5("This is an <h5> element."),
        H6("This is an <h6> element."),
        H3(Code("HTML")),
        HTML("This is some free HTML, with <a>A</a>, <b>B</b>, <i>I</i>, <u>U</U> etc."),
        H3(Code("Img")),
        Img(src="/img/favicon.png", alt="This is an <img> element."),
        H3(Code("Input")),
        Input("button"),
        Input("checkbox"),
        Input("color"),
        Input("date"),
        Input("datetime-local"),
        Input("email"),
        Input("file"),
        Input("hidden"),
        Input("month"),
        Input("number"),
        Input("password"),
        Input("radio"),
        Input("range"),
        Input("reset"),
        Input("search"),
        Input("submit"),
        Input("tel"),
        Input("text"),
        Input("time"),
        Input("url"),
        Input("week"),
        H3(Code("Label")),
        Label("This is a <label> element."),
        H3(Code("Li"), ", ", Code("Ol"), " and ", Code("Ul")),
        Ul(Li("This is a <li> element inside <ul>."), Li("This is another <li> element.")),
        Ol(Li("This is a <li> element inside <ol>."), Li("This is another <li> element.")),
        H3(Code("P")),
        P("This is a <p> element."),
        H3(Code("Pre")),
        Pre("This is a <pre> element.\nThis should be on a new line."),
        H3(Code("Select")),
        Select(["This is a <select> element.", "Yes, it really is.", "Are you sure?", "Yes, I am sure."]),
        H3(Code("Span")),
        Span("This is a <span> element."),
        H3(Code("Table"), ", ", Code("Tr"), ", ", Code("Th"), ", and ", Code("Td")),
        Table(
            Tr(Th("This is a <th> element."), Th("This is another <th> element.")),
            Tr(Td("This is a <td> element."), Td("This is another <td> element.")),
        ),
        H3(Code("Textarea")),
        Textarea("This is a <textarea> element."),
    )
