from slash.core import Elem
from slash.html import Code, Div, Option, P, Select, Span


def test_select() -> Elem:
    return Div(
        P("This page tests the ", Code("Select"), " element."),
        select := Select(
            [
                Option("Select a bird ..", disabled=True, hidden=True),
                Option("W..dp.ck.r", value="Woodpecker"),
                Option("P.g..n", value="Pigeon"),
                Option("Peacock", disabled=True),
                Option("Rooster"),
                Option("Vulture"),
                Option("Swallow"),
                Option("Seagull"),
                Option("Quail"),
                Option("Duck"),
                Option("Pelican"),
                Option("Magpie"),
                Option("Parrot"),
                Option("Turkey"),
                Option("Crane"),
                Option("Kingfisher"),
                Option("Hummingbird"),
                Option("Sparrow"),
                Option("Cormorant"),
                Option("Ostrich"),
                Option("Crow"),
                Option("Raven"),
                Option("Dove"),
                Option("Hen"),
                Option("Nightingale"),
                Option("Eagle"),
                Option("Swan"),
                Option("Penguin"),
                Option("Flamingo"),
                Option("Goose"),
                Option("Cuckoo"),
                Option("Owl"),
                Option("Hawk"),
                Option("Partridge"),
                Option("Goldfinch"),
                Option("Robin"),
                Option("Finch"),
                Option("Frigatebird"),
                Option("Sandpiper"),
                Option("Stork"),
                Option("Ibis"),
                Option("Hornbill"),
                Option("Bulbul"),
                Option("Skylark"),
                Option("Canary"),
                Option("Wagtail"),
                Option("Starling"),
                Option("Macaw"),
                Option("Cockatoo"),
                Option("Heron"),
                Option("Toucan"),
                Option("Jay"),
                Option("Mynah"),
                Option("Cardinal"),
                Option("Chickadee"),
                Option("Junco"),
                Option("Bluebird"),
                Option("Swift"),
                Option("Gull"),
                Option("Lovebird"),
                Option("Spoonbill"),
                Option("Kiwi"),
                Option("Avocet"),
                Option("Wren"),
                Option("Mockingbird"),
                Option("Pheasant"),
                Option("Hoopoe"),
                Option("Kite"),
                Option("Peahen"),
                Option("Falcon"),
                Option("Mallard"),
                Option("Bald eagle"),
                Option("Tern"),
                Option("Night hawk"),
                Option("Crossbill"),
                Option("Lapwing"),
                Option("Puffin"),
                Option("Koyal"),
                Option("Bullfinch"),
                Option("Emu"),
                Option("Condor"),
            ]
        ).onchange(
            lambda: span.set_text(f"You selected '{select.value}'"),
        ),
        span := Span().style({"padding": "8px"}),
    ).style({"text-align": "center"})
