from slash.core import Elem
from slash.html import H2, Div, Select, Span


def test_select() -> Elem:
    return Div(
        H2("Select"),
        select := Select(
            [
                "Woodpecker",
                "Pigeon",
                "Peacock",
                "Rooster",
                "Vulture",
                "Swallow",
                "Seagull",
                "Quail",
                "Duck",
                "Pelican",
                "Magpie",
                "Parrot",
                "Turkey",
                "Crane",
                "Kingfisher",
                "Hummingbird",
                "Sparrow",
                "Cormorant",
                "Ostrich",
                "Crow",
                "Raven",
                "Dove",
                "Hen",
                "Nightingale",
                "Eagle",
                "Swan",
                "Penguin",
                "Flamingo",
                "Goose",
                "Cuckoo",
                "Owl",
                "Hawk",
                "Partridge",
                "Goldfinch",
                "Robin",
                "Finch",
                "Frigatebird",
                "Sandpiper",
                "Stork",
                "Ibis",
                "Hornbill",
                "Bulbul",
                "Skylark",
                "Canary",
                "Wagtail",
                "Starling",
                "Macaw",
                "Cockatoo",
                "Heron",
                "Toucan",
                "Jay",
                "Mynah",
                "Cardinal",
                "Chickadee",
                "Junco",
                "Bluebird",
                "Swift",
                "Gull",
                "Lovebird",
                "Spoonbill",
                "Kiwi",
                "Avocet",
                "Wren",
                "Mockingbird",
                "Pheasant",
                "Hoopoe",
                "Kite",
                "Peahen",
                "Falcon",
                "Mallard",
                "Bald eagle",
                "Tern",
                "Night hawk",
                "Crossbill",
                "Lapwing",
                "Puffin",
                "Koyal",
                "Bullfinch",
                "Emu",
                "Condor",
            ]
        ).onchange(
            lambda: span.set_text(f"You selected '{select.value}'"),
        ),
        span := Span().style({"padding": "8px"}),
    )
